name: test-setup
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - alabaster=1.0.0
  - annotated-types=0.7.0
  - aom=3.9.1
  - app-model=0.4.0
  - appdirs=1.4.4
  - appnope=0.1.4
  - asciitree=0.3.3
  - asttokens=3.0.1
  - attrs=25.4.0
  - babel=2.17.0
  - backports.zstd=1.2.0
  - bermuda=0.1.6
  - blosc=1.21.6
  - brotli-python=1.2.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-blosc2=2.15.2
  - ca-certificates=2025.12.2
  - cachey=0.2.1
  - certifi=2025.11.12
  - charls=2.4.2
  - charset-normalizer=3.4.4
  - click=8.3.1
  - cloudpickle=3.1.2
  - colorama=0.4.6
  - comm=0.2.3
  - cyrus-sasl=2.1.28
  - cytoolz=1.1.0
  - dask-core=2025.11.0
  - dav1d=1.2.1
  - debugpy=1.8.17
  - decorator=5.2.1
  - docstring_parser=0.17.0
  - docutils=0.21.2
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - expat=2.7.3
  - fasteners=0.19
  - flexcache=0.3
  - flexparser=0.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.1
  - freetype-py=2.5.1
  - fsspec=2025.12.0
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - giflib=5.2.2
  - glib=2.84.4
  - glib-tools=2.84.4
  - gst-plugins-base=1.24.11
  - gstreamer=1.24.11
  - h2=4.3.0
  - heapdict=1.0.1
  - hpack=4.1.0
  - hsluv=5.0.4
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - imagesize=1.4.1
  - importlib-metadata=8.7.0
  - in-n-out=0.2.1
  - ipykernel=6.31.0
  - ipython=8.37.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jupyter_client=8.7.0
  - jupyter_core=5.9.1
  - jxrlib=1.1
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.17
  - lerc=4.0.0
  - libaec=1.1.4
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libavif16=1.3.0
  - libblas=3.11.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.11.0
  - libclang-cpp17=17.0.6
  - libclang13=19.1.7
  - libcxx=20.1.8
  - libdeflate=1.22
  - libedit=3.1.20250104
  - libexpat=2.7.3
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.84.4
  - libhwy=1.3.0
  - libiconv=1.18
  - libintl=0.25.1
  - libintl-devel=0.25.1
  - libjpeg-turbo=3.1.2
  - libjxl=0.11.1
  - liblapack=3.11.0
  - libllvm17=17.0.6
  - libllvm19=19.1.7
  - libntlm=1.8
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopus=1.5.2
  - libpng=1.6.53
  - libpq=17.7
  - libsodium=1.0.20
  - libsqlite=3.51.1
  - libtiff=4.7.0
  - libvorbis=1.3.7
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.13.5
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - llvm-openmp=21.1.7
  - llvmlite=0.46.0
  - locket=1.0.0
  - lz4-c=1.9.4
  - magicgui=0.10.1
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - matplotlib-inline=0.2.1
  - mdurl=0.1.2
  - msgpack-python=1.1.2
  - napari=0.6.6
  - napari-base=0.6.6
  - napari-console=0.1.4
  - napari-plugin-engine=0.2.0
  - napari-plugin-manager=0.1.8
  - napari-svg=0.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - npe2=0.7.9
  - nspr=4.38
  - nss=3.118
  - numba=0.63.0
  - numcodecs=0.13.1
  - numpy=2.2.6
  - numpydoc=1.10.0
  - openjpeg=2.5.3
  - openldap=2.6.10
  - openssl=3.6.0
  - packaging=25.0
  - pandas=2.3.3
  - parso=0.8.5
  - partd=1.4.2
  - partsegcore-compiled-backend=0.15.14
  - pcre2=10.46
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pint=0.24.4
  - pip=25.3
  - platformdirs=4.5.1
  - ply=3.11
  - pooch=1.8.2
  - prompt-toolkit=3.0.52
  - psutil=7.1.3
  - psygnal=0.15.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyconify=0.2.1
  - pydantic=2.12.5
  - pydantic-compat=0.1.2
  - pydantic-core=2.41.5
  - pygments=2.19.2
  - pyopengl=3.1.10
  - pyproject_hooks=1.2.0
  - pyqt=5.15.11
  - pyqt5-sip=12.17.0
  - pysocks=1.7.1
  - python=3.10.15
  - python-build=1.3.0
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytz=2025.2
  - pywavelets=1.8.0
  - pywin32=311
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qt-main=5.15.15
  - qtconsole-base=5.7.0
  - qtpy=2.4.3
  - rav1e=0.7.1
  - readline=8.3
  - referencing=0.37.0
  - requests=2.32.5
  - rich=14.2.0
  - rpds-py=0.30.0
  - scikit-image=0.25.2
  - setuptools=80.9.0
  - shellingham=1.5.4
  - sip=6.15.0
  - six=1.17.0
  - snappy=1.2.2
  - snowballstemmer=3.0.1
  - sphinx=8.1.3
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=1.1.10
  - sqlite=3.51.0
  - stack_data=0.6.3
  - superqt=0.7.6
  - svt-av1=3.1.2
  - tk=8.6.15
  - toml=0.10.2
  - tomli=2.3.0
  - tomli-w=1.2.0
  - toolz=1.1.0
  - tornado=6.5.3
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typer=0.20.0
  - typer-slim=0.20.0
  - typer-slim-standard=0.20.0
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.6.1
  - vispy=0.15.2
  - wcwidth=0.2.14
  - wheel=0.45.1
  - wrapt=2.0.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.4
  - yaml=0.2.5
  - zarr=2.18.3
  - zeromq=4.3.5
  - zfp=1.0.1
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.2.5
  - zstd=1.5.7
  - pip:
      - acvl-utils==0.2.5
      - anyio==4.12.0
      - argparse==1.4.0
      - batchgenerators==0.25.1
      - batchgeneratorsv2==0.3.0
      - blosc2==3.12.2
      - connected-components-3d==3.26.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - dynamic-network-architectures==0.4.2
      - einops==0.8.1
      - fft-conv-pytorch==1.2.0
      - filelock==3.20.0
      - fonttools==4.61.0
      - future==1.0.0
      - graphviz==0.21
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.2.2
      - imagecodecs==2025.3.30
      - imageio==2.37.2
      - importlib-resources==6.5.2
      - joblib==1.5.2
      - linecache2==1.0.0
      - matplotlib==3.10.8
      - mpmath==1.3.0
      - ndindex==1.10.1
      - nibabel==5.3.3
      - nnunetv2==2.6.2
      - numexpr==2.14.1
      - pillow==12.0.0
      - py-cpuinfo==9.0.0
      - pyparsing==3.2.5
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - simpleitk==2.5.3
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - timm==1.0.22
      - torch==2.9.1
      - torchvision==0.24.1
      - traceback2==1.4.0
      - unittest2==1.1.0
      - yacs==0.1.8
